### ISSUE TITLE
Card Component

### ISSUE THREAD

**Issue by edwintcloud** [dins-app/web-app#1]
components/Card.tsx (3 pts)
Type: div, optional props (see Container.tsx)
- [x] margin (from props)[margin: string]
- [x] padding (from props)[padding: string]
- [x] display: grid
- [x] align-self (from props)[alignSelf: string]
- [x] justify-self (from props)[justifySelf: string]
- [x] align-items (from props)[alignItems: string]
- [x] justify-items (from props)[justifyItems: string]
- [x] grid-template-rows (from props)[rows: string]
- [x] grid-template-columns (from props)[cols: string]
- [x] grid-gap (from props)[gap: string]
- [x] border-radius (from props)[borderRadius: string]
- [x] width (from props)[width: string]
- [x] height (from props)[height: string]
- [x] position: relative
- [x] background-color (from props)[color: string]

**Comment by vmarcella** [comment]
fd876e23b8c828bc95511b8a8d2d62df27921f5e meets the specifications of this issue
