### ISSUE TITLE
Button Component

### ISSUE THREAD

**Issue by edwintcloud** [dins-app/web-app#2]
components/Button.tsx (9 pts)
Type: button, optional props (see Container.tsx)
- [x] margin (from props)[margin: string]
- [x] padding (from props)[padding: string]
- [ ] type (from props | default button)[type: string]
- [x] *size (from props | default regular)[size: string]
Size options are small, regular, and large.
- [x] disabled (from props)[disabled: boolean]
- [x] background-color (from props | default dark)[shade: string]
Combined with style below for light, medium, dark, or neutral colored buttons. See the three circular buttons for the three shades. Neutral is the color of the first square button.
- [ ] *style (from props | default regular)[style: string]
Style applies certain styles if set. Options: regular, fab. Default regular button should look like the first button below. With appropriate on hover and selected states. Cursor should be pointer. Fab is the circle button.
![image](https://user-images.githubusercontent.com/16670872/54162978-bcdac780-4414-11e9-9974-c46f910554d8.png)
![image](https://user-images.githubusercontent.com/16670872/54163008-d7ad3c00-4414-11e9-98e7-ac999998847a.png)
![image](https://user-images.githubusercontent.com/16670872/54163038-ea277580-4414-11e9-9e62-4c820b923031.png)
![image](https://user-images.githubusercontent.com/16670872/54163060-fad7eb80-4414-11e9-9942-1e461a3a1dcd.png)

*Note: Feel free to be creative on how these properties can best be applied in a reusable way for our theme/usecase. As a reference [here](https://drive.google.com/file/d/1UF6GbgCf6gSMwRV1idRz8yNZV8S2QOkk/view) is the landing page photo.

**Comment by vmarcella** [comment]
c235dbe27de5a76553fd0a0df25cd57cb52bfb90 addresses approximately 90% of this. I just need clarification on two things.

1. Is `type` referring to the type of html element you want the component to be represented as? If so, that can be done by simply passing `as` as a prop. More can be found here: [Polymorphic prop](https://www.styled-components.com/docs/api#as-polymorphic-prop)

2. What defines an appropriate on hover? I could just use the `props.color` prop to apply the correct effects to the color of the component but i'm not quite sure if more is being requested.

Thanks in advance.

**Comment by edwintcloud** [comment]
1. Awesome solution, as prop works great just be sure to annotate it in the component.
2. Hmm, so usually a hover effect is a few shades darker with a slight alpha decrease (more transparent). It might be easier to test and see how it looks if you use hsla or rgba instead of hex for the color mappings. You could also create some sort of function to just modify the hsla or rgba values by a multiple to achieve the desired effect consistently. Have a look at #8 in this blog post: [10 useful tips for styled components](https://medium.com/@pitipatdop/10-useful-tips-for-styled-components-b7710b021e6a)

**Comment by edwintcloud** [comment]
Closing... effectively complete as of c235dbe
